Repository pivotal-cf/docs-monitoring, pull requests merged in 2019-09, with the labels that each got.

#173 Update alerting recommendation for Syslog Agent Loss Rate
  docs-content/key-cap-scaling.html.md.erb
Labels: in progress

#174 Update alerting recommendation for Syslog Agent Loss Rate
  docs-content/key-cap-scaling.html.md.erb
Labels: in progress

#169 Add note about router vertical scaling
  docs-content/key-cap-scaling.html.md.erb
Labels: scheduled

#175 Fix syslog agent loss rate calculation
  docs-content/key-cap-scaling.html.md.erb
Labels: unscheduled
